import {test,expect} from '@playwright/test';
let errors;
test.beforeEach(async({page})=>{errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/game.html');await page.waitForFunction(()=>window.ARCADE);await page.evaluate(()=>{ARCADE.Sound.on=false;ARCADE.showScreen('ladder');});});
test.afterEach(()=>expect(errors).toEqual([]));
async function controlled(page){await page.evaluate(async()=>{const g=ARCADE.LADDER;await g.start();g.pause(true);g.state.mode='playing';g.state.countdown=0;for(const f of g.state.fighters){f.invuln=0;if(!f.player)f.stun=999;}window.advance=seconds=>{for(let t=0;t<seconds-.0001;t+=.05)g.step(.05);};});}
for(const width of [320,390,1440])test(`Ladder Wars selection and controls fit ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});expect(await page.locator('#lwRoster option').count()).toBe(21);await page.locator('#lwRoster').selectOption('dani-mo');await page.locator('#lwStartBtn').click();await expect(page.locator('#lwSetup')).toBeHidden();expect(await page.evaluate(()=>ARCADE.LADDER.player().id)).toBe('dani-mo');for(const id of ['lwCanvas','lwStick','lwThrowBtn','lwHomeBtn']){const b=await page.locator('#'+id).boundingBox();expect(b.x).toBeGreaterThanOrEqual(0);expect(b.x+b.width).toBeLessThanOrEqual(width);if(width<500)expect(b.y+b.height).toBeLessThan(900);}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);});
test('carry, align, climb and four timed grabs claim the gold once',async({page})=>{await controlled(page);const r=await page.evaluate(()=>{const g=ARCADE.LADDER,s=g.state,p=g.player();g.act('throw');const carrier=s.ladder.carrier;p.x=240;p.y=365;advance(.35);const setHere=document.querySelector('#lwThrowBtn').textContent.includes('SET HERE')&&document.querySelector('#lwThrowBtn').classList.contains('lw-set-ready');g.act('throw');const open=s.ladder.open;advance(.35);g.act('throw');advance(5);const top=p.climb;for(let i=0;i<4;i++){p.cool=0;s.elapsed=0;g.act('throw');}const score=s.score;advance(1);return{carrier,player:p.uid,open,setHere,top,pulls:p.pulls,mode:s.mode,won:s.won,wins:s.wins,score,after:s.score};});expect(r.carrier).toBe(r.player);expect(r.open).toBe(true);expect(r.setHere).toBe(true);expect(r.top).toBe(1);expect(r.pulls).toBe(4);expect(r.mode).toBe('over');expect(r.won).toBe(true);expect(r.wins).toBe(1);expect(r.score).toBeGreaterThan(3000);expect(r.after).toBe(r.score);await page.locator('#lwSaveBtn').click();await page.locator('#lbInitials').fill('GOD');await page.locator('#lbSaveBtn').click();expect(await page.evaluate(()=>ARCADE.LB.board('ladder').length)).toBe(1);});
test('misaligned ladder must be repositioned, and two bad grabs cause a fall',async({page})=>{await controlled(page);const r=await page.evaluate(()=>{const g=ARCADE.LADDER,s=g.state,p=g.player();g.act('throw');advance(.35);g.act('throw');advance(.35);g.act('throw');const carriedAgain=s.ladder.carrier===p.uid;Object.assign(s.ladder,{x:240,y:365,open:true,carrier:null});Object.assign(p,{x:220,y:365,cool:0});g.act('throw');advance(5);for(let i=0;i<2;i++){p.cool=0;s.elapsed=Math.PI/2/4.1;g.act('throw');}return{carriedAgain,climbing:p.climbing,fall:p.fallTime,stun:p.stun,hp:p.hp,pulls:p.pulls};});expect(r.carriedAgain).toBe(true);expect(r.climbing).toBe(false);expect(r.fall).toBeGreaterThan(0);expect(r.stun).toBeGreaterThan(1);expect(r.pulls).toBe(0);});
test('striking the base tips a rival and knocked-down wrestlers recover',async({page})=>{await controlled(page);const r=await page.evaluate(()=>{const g=ARCADE.LADDER,s=g.state,p=g.player(),v=s.fighters[1];Object.assign(s.ladder,{x:240,y:365,open:true});Object.assign(p,{x:210,y:365});Object.assign(v,{x:260,y:365,climbing:true,climb:.8,climbSide:1,stun:0});g.act('hit');advance(.2);const tipped=!v.climbing,open=s.ladder.open;advance(2);Object.assign(v,{hp:1,action:null,stun:0,invuln:0,aiWait:999,x:250,y:365});Object.assign(p,{x:210,y:365,action:null,cool:0,stun:0});g.act('hit');advance(.2);const down=v.action?.kind;advance(7.1);return{tipped,open,down,hp:v.hp,out:v.out};});expect(r.tipped).toBe(true);expect(r.open).toBe(false);expect(r.down).toBe('down');expect(r.hp).toBeGreaterThanOrEqual(55);expect(r.out).toBe(false);});
test('time runs out, replay resets ladder and pause freezes the round',async({page})=>{await controlled(page);await page.evaluate(()=>{const g=ARCADE.LADDER;g.state.elapsed=119.99;advance(.1);});await expect(page.locator('#lwOver')).toBeVisible();await page.locator('#lwAgainBtn').click();await expect(page.locator('#lwOver')).toBeHidden();await page.locator('#lwPauseBtn').click();const before=await page.evaluate(()=>ARCADE.LADDER.state.time);await page.waitForTimeout(150);expect(await page.evaluate(()=>ARCADE.LADDER.state.time)).toBe(before);await page.locator('#lwResumeBtn').click();await expect.poll(()=>page.evaluate(()=>ARCADE.LADDER.state.time)).toBeLessThan(before);});
test('chaos uses four unique wrestlers, bounded effects and finite state offline',async({page,context})=>{await page.locator('#lwSize').selectOption('4');await controlled(page);await context.setOffline(true);const r=await page.evaluate(()=>{const g=ARCADE.LADDER,s=g.state;const ids=new Set(s.fighters.map(f=>f.id)).size;for(const f of s.fighters)f.stun=0;for(let i=0;i<2450&&s.mode==='playing';i++){g.step(.05);if(i%25===0)g.draw();}return{ids,finite:s.fighters.every(f=>Number.isFinite(f.hp)&&Number.isFinite(f.x)&&Number.isFinite(f.climb)),labels:s.labels.length,cache:g.cacheSize(),mode:s.mode};});expect(r.ids).toBe(4);expect(r.finite).toBe(true);expect(r.labels).toBeLessThanOrEqual(12);expect(r.cache).toBeLessThanOrEqual(6);expect(r.mode).toBe('over');});

test('a knockout creates enough time to climb and win before the rival recovers',async({page})=>{await controlled(page);const r=await page.evaluate(()=>{const g=ARCADE.LADDER,s=g.state,p=g.player(),v=s.fighters[1];Object.assign(s.ladder,{x:240,y:365,open:true});Object.assign(p,{x:217,y:365});Object.assign(v,{x:260,y:365,hp:1,stun:0});g.act('hit');advance(.5);g.act('throw');for(let i=0;i<150&&s.mode==='playing';i++){if(p.climb>=1&&p.cool<=0&&g.grabNeedle(p)>.42&&g.grabNeedle(p)<.6)g.act('throw');advance(.05);}return{won:s.won,pulls:p.pulls,elapsed:s.elapsed,rivalDown:v.stun>0};});expect(r.won).toBe(true);expect(r.pulls).toBe(4);expect(r.rivalDown).toBe(true);});
